name: Build arm64 Deb and Extract Dylib

on: 
  push:
    branches: 
      - private
  workflow_dispatch:  # 手动触发开关
  
jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          submodules: true

      - name: Check cache
        run: |
          echo upstream_heads=`git ls-remote https://github.com/roothide/theos | head -n 1 | cut -f 1`-`git ls-remote https://github.com/theos/sdks | head -n 1 | cut -f 1` >> $GITHUB_ENV

      - name: Use cache
        id: cache
        uses: actions/cache@v4.2.1
        with:
          path: ${{ github.workspace }}/theos
          key: ${{ runner.os }}-${{ env.upstream_heads }}

      - name: Prepare Theos
        uses: huami1314/theos-action@main

      - name: Setup GNU Make
        run: |
          echo "$(brew --prefix)/opt/make/libexec/gnubin" >> $GITHUB_PATH

      - name: Build arm64 package
        run: |
          rm -f packages/*
          # 只构建arm64架构的包
          make package ARCHS=arm64 FINALPACKAGE=1 -j$(sysctl -n hw.ncpu)
          make package ARCHS=arm64 THEOS_PACKAGE_SCHEME=rootless FINALPACKAGE=1 -j$(sysctl -n hw.ncpu)
          make package ARCHS=arm64 THEOS_PACKAGE_SCHEME=roothide FINALPACKAGE=1 -j$(sysctl -n hw.ncpu)

      - name: Extract dylib from deb
        run: |
          mkdir -p extracted_libs
          # 找到最新生成的deb文件
          DEB_FILE=$(ls -t packages/*.deb | head -n1)
          # 临时解压deb包
          dpkg-deb -x $DEB_FILE temp_deb
          # 查找并复制所有.dylib文件
          find temp_deb -name "*.dylib" -exec cp {} extracted_libs/ \;
          # 清理临时文件
          rm -rf temp_deb
          # 确保只保留一个dylib文件（如果有多个）
          DYLIB_FILE=$(ls extracted_libs/*.dylib | head -n1)
          if [ -f "$DYLIB_FILE" ]; then
            mv "$DYLIB_FILE" extracted_libs/library.dylib
            rm -f extracted_libs/*.dylib
            mv extracted_libs/library.dylib extracted_libs/
          fi

      - name: Upload Deb package
        uses: actions/upload-artifact@v4.6.0
        with:
          name: arm64-package
          path: ${{ github.workspace }}/packages/*.deb
          retention-days: 1

      - name: Upload Dylib
        uses: actions/upload-artifact@v4.6.0
        with:
          name: arm64-library
          path: ${{ github.workspace }}/extracted_libs/*.dylib
          retention-days: 1